import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises';
test('configurador ofrece balines, colores, dijes, talla y WhatsApp oficial',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),script=await readFile(new URL('../public/customizer.js',import.meta.url),'utf8');for(const text of ['Balines lisos','Balines diamantados','Elige el color del tejido','Elige un dije','Medida de muñeca'])assert.ok(html.includes(text));assert.ok(script.includes('573175697698'));assert.ok(script.includes('encodeURIComponent'));assert.ok(html.includes('vista previa es una guía'))});

test('configurador muestra ejemplos visuales identificados como referencia',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');for(const asset of ['manilla-lisos-ejemplo.webp','manilla-diamantados-ejemplo.webp','manilla-combinados-ejemplo.webp'])assert.ok(html.includes(asset));assert.ok(html.includes('no representan inventario exacto'))});

test('configurador 3D reacciona a opciones y permite girar la manilla',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),script=await readFile(new URL('../public/customizer.js',import.meta.url),'utf8');assert.ok(html.includes('braceletCanvas'));assert.ok(html.includes('Arrastra para girar'));for(const behavior of ['getContext','createRadialGradient','pointermove','ResizeObserver','dataset.symbol'])assert.ok(script.includes(behavior))});

test('personalizador permite manillas, anillos y cuatro tipos de tejido',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),script=await readFile(new URL('../public/customizer.js',import.meta.url),'utf8');for(const option of ['Manilla tejida','Anillo tejido','Nudo tradicional','Tejido doble','Trenzado','Espiral'])assert.ok(html.includes(option));for(const behavior of ['sizeOptions','Talla del anillo','Tipo de tejido','data.get(\'item\')','data.get(\'weave\')'])assert.ok(script.includes(behavior))});

test('permite probar el diseño en una mano 3D de mujer y de hombre',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),script=await readFile(new URL('../public/customizer.js',import.meta.url),'utf8'),css=await readFile(new URL('../public/customizer.css',import.meta.url),'utf8');for(const option of ['En mano de mujer','En mano de hombre','hand-model','ring-finger'])assert.ok(html.includes(option));for(const behavior of ['handX','handY','pointermove','ring-mode','bracelet-mode',"data.get('view')"])assert.ok(script.includes(behavior));for(const visual of ['perspective:720px','transform-style:preserve-3d','weave-braided'])assert.ok(css.includes(visual))});

test('personalizador evita la colisión con elements.item y permite estilos 3D dinámicos',async()=>{const script=await readFile(new URL('../public/customizer.js',import.meta.url),'utf8'),server=await readFile(new URL('../src/server.js',import.meta.url),'utf8');assert.ok(script.includes("namedItem('item').value"));assert.equal(script.includes('form.elements.item.value'),false);assert.ok(server.includes("style-src 'self' 'unsafe-inline'"));assert.ok(server.includes("script-src 'self'"))});

test('la tienda completa productos sin foto con referencias visuales',async()=>{const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),script=await readFile(new URL('../public/app.js',import.meta.url),'utf8');for(const asset of ['catalogo-aretes-v1.webp','catalogo-pulsera-v1.webp','catalogo-anillo-v1.webp','catalogo-cadena-v1.webp','catalogo-manilla-v1.webp','catalogo-peluche-v1.webp','catalogo-belleza-v1.webp','catalogo-regalo-v1.webp'])assert.ok(script.includes(asset));for(const icon of ['icono-transferencia.svg','icono-billetera.svg','icono-seguro.svg'])assert.ok(html.includes(icon));assert.ok(script.includes('Imagen de referencia'));assert.ok(html.includes('fotografías reales pueden cargarse'))});
